"""Change tipo_movimiento to Boolean

Revision ID: 2e84773f3c82
Revises: 7a5f10cc33ba
Create Date: 2024-07-31 18:41:08.805245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e84773f3c82'
down_revision = '7a5f10cc33ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tipo_movimiento', sa.Boolean(), nullable=False))
        batch_op.drop_column('cantidad_disponible')
        batch_op.drop_column('ubicacion_almacen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion_almacen', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('cantidad_disponible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('tipo_movimiento')
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###
