"""quitamos detalle de Compra

Revision ID: 672eb87a5492
Revises: a476f59899f5
Create Date: 2024-08-08 11:02:04.805144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672eb87a5492'
down_revision = 'a476f59899f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detalle', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra', schema=None) as batch_op:
        batch_op.drop_column('detalle')

    # ### end Alembic commands ###
