"""Agrega campo costo a la tabla Equipo

Revision ID: 744c09364398
Revises: e7c01cee8615
Create Date: 2024-08-07 15:32:51.769207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744c09364398'
down_revision = 'e7c01cee8615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_column('costo')

    # ### end Alembic commands ###
