"""creacion vehiculo

Revision ID: 947becff32bf
Revises: 
Create Date: 2024-06-25 22:12:36.082142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947becff32bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.Integer(), nullable=True),
    sa.Column('cilindrada', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehiculo')
    # ### end Alembic commands ###
