"""eliminamos campos a tabla Equipo

Revision ID: a476f59899f5
Revises: fe2ce9b9f810
Create Date: 2024-08-07 21:18:46.823771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a476f59899f5'
down_revision = 'fe2ce9b9f810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_column('conectividad')
        batch_op.drop_column('procesador')
        batch_op.drop_column('sistema_operativo')
        batch_op.drop_column('tipo_pantalla')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_pantalla', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('sistema_operativo', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('procesador', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('conectividad', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
