"""cambio modelo

Revision ID: a8570ddeadd4
Revises: b123905ac518
Create Date: 2024-08-02 01:17:20.553866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8570ddeadd4'
down_revision = 'b123905ac518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_constraint('equipo_ibfk_1', type_='foreignkey')
        batch_op.drop_column('id_categoria')

    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_categoria', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'categoria', ['id_categoria'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_categoria')

    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_categoria', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('equipo_ibfk_1', 'categoria', ['id_categoria'], ['id'])

    # ### end Alembic commands ###
