"""iniciando

Revision ID: b123905ac518
Revises: 
Create Date: 2024-08-02 01:13:17.282336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b123905ac518'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_accesorio', sa.String(length=255), nullable=False),
    sa.Column('compatibilidad_modelo', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caracteristica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_caracteristica', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_categoria', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fabricante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_fabricante', sa.String(length=255), nullable=False),
    sa.Column('pais_origen', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_marca', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_proveedor', sa.String(length=255), nullable=False),
    sa.Column('contacto', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_modelo', sa.String(length=255), nullable=False),
    sa.Column('id_fabricante', sa.Integer(), nullable=False),
    sa.Column('id_marca', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_fabricante'], ['fabricante.id'], ),
    sa.ForeignKeyConstraint(['id_marca'], ['marca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accesorio__modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_accesorio', sa.Integer(), nullable=False),
    sa.Column('id_modelo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_accesorio'], ['accesorio.id'], ),
    sa.ForeignKeyConstraint(['id_modelo'], ['modelo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_marca', sa.Integer(), nullable=False),
    sa.Column('id_modelo', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('costo', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['id_marca'], ['marca.id'], ),
    sa.ForeignKeyConstraint(['id_modelo'], ['modelo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipo__caracteristica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.Column('id_caracteristica', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_caracteristica'], ['caracteristica.id'], ),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedor__equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipo.id'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    op.drop_table('proveedor__equipo')
    op.drop_table('equipo__caracteristica')
    op.drop_table('equipo')
    op.drop_table('accesorio__modelo')
    op.drop_table('modelo')
    op.drop_table('proveedor')
    op.drop_table('marca')
    op.drop_table('fabricante')
    op.drop_table('categoria')
    op.drop_table('caracteristica')
    op.drop_table('accesorio')
    # ### end Alembic commands ###
