"""activo boolean en proveedor

Revision ID: bd5ccaa6cdcb
Revises: ef74f95c85b5
Create Date: 2024-08-06 22:15:36.106641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5ccaa6cdcb'
down_revision = 'ef74f95c85b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
