""", unique=True

Revision ID: e5f2311d17c9
Revises: 01d1db41e62a
Create Date: 2024-08-08 14:04:12.219464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f2311d17c9'
down_revision = '01d1db41e62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre_categoria'])

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre_cliente'])

    with op.batch_alter_table('fabricante', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre_fabricante'])
        batch_op.create_unique_constraint(None, ['pais_origen'])

    with op.batch_alter_table('marca', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre_marca'])

    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre_modelo'])

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre_proveedor'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('marca', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('fabricante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
