"""Initial migration

Revision ID: e7c01cee8615
Revises: 
Create Date: 2024-08-07 14:43:17.702462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c01cee8615'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_categoria', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=255), nullable=False),
    sa.Column('condicion_fiscal', sa.String(length=255), nullable=False),
    sa.Column('contacto', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fabricante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_fabricante', sa.String(length=255), nullable=False),
    sa.Column('pais_origen', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_marca', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_proveedor', sa.String(length=255), nullable=False),
    sa.Column('condicion_fiscal', sa.String(length=255), nullable=False),
    sa.Column('contacto', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_comprobante', sa.String(length=255), nullable=False),
    sa.Column('numero_factura', sa.String(length=255), nullable=False),
    sa.Column('detalle', sa.String(length=255), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_factura')
    )
    op.create_table('modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_modelo', sa.String(length=255), nullable=False),
    sa.Column('id_fabricante', sa.Integer(), nullable=False),
    sa.Column('id_marca', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['id_fabricante'], ['fabricante.id'], ),
    sa.ForeignKeyConstraint(['id_marca'], ['marca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_comprobante', sa.String(length=255), nullable=False),
    sa.Column('numero_factura', sa.String(length=255), nullable=False),
    sa.Column('detalle', sa.String(length=255), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_factura')
    )
    op.create_table('equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_marca', sa.Integer(), nullable=False),
    sa.Column('id_modelo', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_marca'], ['marca.id'], ),
    sa.ForeignKeyConstraint(['id_modelo'], ['modelo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle__compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_compra'], ['compra.id'], ),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle__venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipo.id'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle__venta')
    op.drop_table('detalle__compra')
    op.drop_table('equipo')
    op.drop_table('venta')
    op.drop_table('modelo')
    op.drop_table('compra')
    op.drop_table('proveedor')
    op.drop_table('marca')
    op.drop_table('fabricante')
    op.drop_table('cliente')
    op.drop_table('categoria')
    # ### end Alembic commands ###
