"""activo boolean en equipo

Revision ID: ef74f95c85b5
Revises: b304acff8f7d
Create Date: 2024-08-06 22:03:03.946953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef74f95c85b5'
down_revision = 'b304acff8f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False))
        batch_op.drop_column('costo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costo', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
