"""sacamos detalles de la tabla venta

Revision ID: fddca5e640ef
Revises: e5f2311d17c9
Create Date: 2024-08-09 16:16:09.208507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fddca5e640ef'
down_revision = 'e5f2311d17c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('detalle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detalle', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
