"""Agrega campos a tabla Equipo

Revision ID: fe2ce9b9f810
Revises: 744c09364398
Create Date: 2024-08-07 17:25:12.967785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2ce9b9f810'
down_revision = '744c09364398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('tamano_pantalla', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('memoria', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('procesador', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('camara_delantera', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('camara_trasera', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('conectividad', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('sistema_operativo', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('capacidad_bateria', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('tipo_pantalla', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_column('tipo_pantalla')
        batch_op.drop_column('capacidad_bateria')
        batch_op.drop_column('sistema_operativo')
        batch_op.drop_column('conectividad')
        batch_op.drop_column('camara_trasera')
        batch_op.drop_column('camara_delantera')
        batch_op.drop_column('procesador')
        batch_op.drop_column('memoria')
        batch_op.drop_column('tamano_pantalla')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
